version: '2'
services:
    word-count-topology:
        container_name: word-count-topology
        image: fhuz/docker-storm
        entrypoint:
            - storm
        volumes:
            - /vagrant/WordCount/target/:/home/storm
        command: -c nimbus.host=10.10.20.10 jar /home/storm/WordCount-1.0-SNAPSHOT-jar-with-dependencies.jar com.microsoft.example.WordCountTopology